version: '3.0'
services:
    nginx-php7:
        build: ./.docker
        environment:
            - PHP_XDEBUG=false
            - TZ=America/Sao_Paulo
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes: ['./:/var/www/']
        networks:
            - laravel

    mysql:
      image: mysql:5.7.26
      environment:
        - MYSQL_ROOT_PASSWORD=root123
        - MYSQL_DATABASE=laravel
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root123
        - TZ=America/Sao_Paulo
      ports:
        - 33061:3306
      volumes:
        - mysql:/var/lib/mysql
      networks:
        - laravel

    mailhog:
      image: mailhog/mailhog:latest
      restart: always
      ports:
        - 1025:1025
        - 8025:8025
      networks:
        - laravel

volumes:
  mysql:

networks:
    laravel:
        driver: bridge
